apiVersion: v2
appVersion: 2.11.2
description: A Helm chart for multicluster-engine - CRDs
keywords:
- mce
- multicluster-engine
- multiclusterengine
name: multicluster-engine-crds
sources:
- quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mce-operator-bundle-mce-211@sha256:bc8c5a28e5142e0a9a8b015cfaebfa47937f1749957cd91cd578188c3aa865da
type: application
version: 2.11.2
